- name: Reload systemd user daemon (Root Proxy Method)
  become: true
  ansible.builtin.command:
    cmd: systemctl --user -M minecraft-srv@.host daemon-reload

- name: Reload nftables
  become: true
  ansible.builtin.service:
    name: nftables
    state: reloaded
